### ISSUE TITLE
[Question] Is there a way to use webview in place of TWA?

### ISSUE THREAD

**Issue by davidmaxwaterman** [pwa-builder/CloudAPK#16]
**Question in detail**
We have hit a problem that is caused by this tool using a TWA instead of a webview. TWAs seem to require chrome installed and a profile to be set up. Installing chrome using a script is not difficult, but setting up a user profile for chrome is more problematic.

Is there a way to have this tool use a webview instead of a TWA?

**Is your question related to a problem? Please describe.**
We have thousands of android phones that are handed out to different people daily (perhaps more frequently than that), and handed back later in the day. User profiles provide no added value, but require some effort to set up - manual effort is out of the question and it must be scriptable. Ideally, we'd prefer to avoid this whole TWA thing since it requires extra effort (needs a profile and an extra file on the server, etc).

**Describe alternatives you've considered**
Manual creation of the profile on each phone is out of the question.
Perhaps there's a way to create a profile using a script - eg like copying ~/.config/google-chrome/Default, or something along those lines?
It just seems like this TWA thing is adding effort for no benefit (in my situation), and having the option to use a webview would be useful.

**Comment by JudahGabriel** [comment]
You can still use the old web view:

![image](https://user-images.githubusercontent.com/312936/75804407-bedc1b80-5d34-11ea-86a2-b5fc24e795d1.png)

**Comment by davidmaxwaterman** [comment]
Hi, Sorry...but where is that UI? I'm using CloudAPK (per this issue) and there's no UI since it's a cloud service. I just use curl to send a request, the service builds and apk and send it back to curl to download...or words to that effect. Perhaps if that UI is for a service using CloudAPK, I can take a look to see what JSON it sends to CloudAPK?
It is reassuring that it looks like this is possible, but how do I do that from curl? I guess there must be an option in the json, but I don't see that in the json on here:
https://github.com/pwa-builder/CloudAPK

**Comment by JudahGabriel** [comment]
That UI is in PWABuilder's download Android package. Once you analyze your URL, click **Build My PWA**, then click **Android**. The above UI will appear and let you download a webview.

Please note that both Google and we at PWABuilder don't recommend webview for Android.

**Comment by davidmaxwaterman** [comment]
OK, I've not tried PWABuilder...I am only interested in CloudAPK...but I can probably check the code if you can't tell me explicitly what I need to do.

Yes, I understand Google and a perhaps you have a vested interest in forcing the user into the browser, but it doesn't apply for all use-cases. Forcing the user into the browser requires a browser that supports service worker, etc, not to mention that they need user interaction to set up, extra effort on our server, and/or use of EEM. It's a huge increase in effort if you don't actually need or want the benefits. TBH, I'm not even sure why you mention that. Are you suggesting webviews will be deprecated at some point?

**Comment by davidmaxwaterman** [comment]
OK, I found where that code is:

https://github.com/pwa-builder/PWABuilder/blob/master/components/Download.vue#L180

but where is 'this.build()'?

It'd be great if someone could tell me how to make CloudAPK do this.

**Comment by JudahGabriel** [comment]
I understand there are some scenarios where webview is the better option. It's why we left it as an option in PWABuilder. (FWIW, CloudAPK is built for use in PWABuilder, in case that's not clear.)

With regards to TWA over webview, we know that it's Google's recommended way of getting PWAs into their Store. Based on their recommendation to us, we pass that on to devs who use PWABuilder. Whether webviews will be deprecated is something Google would have to answer. I'd guess not because there remains valid scenarios for using them, as you point out.

As for using curl, it's cool you're doing that. It's not really supported? :-) But if it's working for you, sure, roll with it. Feel free to inspect how PWABuilder does it and follow that. Let me know if you run into issues.

**Comment by davidmaxwaterman** [comment]
> (FWIW, CloudAPK is built for use in PWABuilder, in case that's not clear.)

I had assumed it was, but I was starting to wonder.

> As for using curl, it's cool you're doing that. It's not really supported?

I'm not sure I get you there. I'm not using curl because it is my end goal. We want a button on our web site that pops out an apk from the pwa the user is configuring. PWABuilder doesn't seem to do that...it produces a zip which still needs to be made into an apk, but I guess it's similar in intent at least.
So, our b/e would make a call to our own hosted version of CloudAPK and it would spit out an APK. I've followed the instructions to get the docker thing going, and I've used curl to test it will work, and it does, but it produces an APK that uses a TWA, rather than a webview.
It's clear, I think, that PWABuilder perhaps uses CloudAPK to produce APKs that use TWAs, but I'm not entirely sure if PWABuilder uses CloudAPK to produce the webview APKs, since I don't see a documented option for that.

If no one can point me in the right direction, then I guess I will have to continue digging through the code myself. I'm a front-end dev, and this pesky virus thing has resulted in us being short staffed on the back-end...it's all a little unfamiliar.

**Comment by andreban** [comment]
Hi @davidmaxwaterman ,

Thanks for the inputs, I do think the question on WebView vs Trusted Web Activity is a fair one and plan to document this better soon. 

> Yes, I understand Google and a perhaps you have a vested interest in forcing the user into the browser

The Android WebView is not designed as a tool to build browsers and, even though we make the best effort to be compatible, it doesn't support many of the modern Web APIs (eg: push notifications). Progressive Web Apps (PWAs), make extensive use of those APIs and opening them inside a WebView will provide an inferior experience to users than what the PWA author intended, if not broken. So, the goal with Trusted Web Activity is providing the best experience to users, the way the developer building the PWA intended. This is what makes Trusted Web Activity the recommended way of wrapping PWAs into an Android App.

> but it doesn't apply for all use-cases. Forcing the user into the browser requires a browser that supports service worker, etc, so that needs to be installed (in our case) not to mention that the browsers need user interaction to set up (and/or use of EEM), and extra effort on our server config. It's a huge increase in effort if you don't actually need or want the benefits. TBH, I'm not even sure why you mention that.

I agree it may not be the best solution for all use-cases, and Android offers many alternatives. From using the WebView, to using alternatives like [GeckoView](https://wiki.mozilla.org/Mobile/GeckoView), or even shipping your own browser engine with the Android App. Each comes with its own upsides and downsides. Most alternatives will mean a lot more work to develop the Android App though.

More specifically on when to use the Android WebView, content opened inside the WebView should be developed with the WebView as a target, including doing QA tests to check if the content works as expected and implementing workarounds when needed. Developers shouldn't expect content created for the Web Platform to just work in the WebView, as it doesn't fully support all Web API. This is usually the case with PWAs.

**On the `assetlinks.json` file:**
The problem that `assetlinks.json` solves is that a PWA developer probably wouldn't happy with an unknown developer building an Android App out of their PWA, without their knowledge.  This would also likely break [Play Store policies on impersonation](https://play.google.com/about/ip-impersonation/). The Asset Links validation ensures this doesn't happen.

This would also be needed anyway when using the WebView or other alternatives, in order to set the application as the default handler for links to the app, using [AppLinks](https://developer.android.com/training/app-links).

Having said that, we do agree setting up this file is one of the biggest pain points when building an App that uses Trusted Web Activity, and we're actively looking into ways of making it easier for developers.

**Compatibility:**
Browser compatibility for Trusted Web Activity is something that is improving, and other browsers are also implementing support for Trusted Web Activity (eg: [Firefox Preview Nightly](https://play.google.com/store/apps/details?id=org.mozilla.fenix.nightly)).  Most Android browsers have good PWA support, including Service Worker and we'd expect the vast majority of users to already have been through the first-run experience. 

I do think that, as a tool aimed to help developers creating Progressive Web Apps to create an Android App, Trusted Web Activity is the best solution for PWABuilder. It seems to me other use-cases would be outside the scope of PWABuilder or CloudAPK.

Finally, I don't fully understand your use-case. But I think I'm most likely missing context here and I would be interested in learning more. I'm not sure if this is the right forum for this though, so feel free to send more over email.

> Are you suggesting webviews will be deprecated at some point?

No, there are no plans to deprecate the Android WebView. Those are just tools optimised for different jobs.

**Comment by davidmaxwaterman** [comment]
This is really valuable input. Thank you for spending the time to respond so comprehensively. I think you make a convincing case for TWAs.

> I'm not sure if this is the right forum for this though, so feel free to send more over email.

Yes, you're probably correct. I am reluctant to spell things out quite as much as I would like to because it is so public.  I wonder how to find your email...mine is the same as my github username at gmail, if you wouldn't mind initiating.
