### ISSUE TITLE
APK splash ratio / sharpness

### ISSUE THREAD

**Issue by peterpeterparker** [pwa-builder/CloudAPK#19]
**Describe the bug**
The aspect ratio of the splash screen doesn't seems to be respected while creating a APK/TWA from a PWA with the PWABuilder.

See screenshots, this has for effect to generate a splash which is not sharp enough

**To Reproduce**
1. Go to https://www.pwabuilder.com/
2. Generate a TWA for https://deckdeckgo.com

**Expected behavior**
A sharp splash screen 

**Screenshots**

APK:

![Screenshot_20200420-201215](https://user-images.githubusercontent.com/16886711/79785251-d18dcc80-8343-11ea-96c6-3fe1ad95c6ee.jpg)

PWA:

![Screenshot_20200420-201553](https://user-images.githubusercontent.com/16886711/79785270-dd798e80-8343-11ea-9e60-45c1e77236d0.jpg)

**Comment by jgw96** [comment]
Hmmm @peterpeterparker , it should be using your 512x512 icon from your manifest https://github.com/pwa-builder/PWABuilder/blob/master/components/Download.vue#L97, is that icon blurry outside of the TWA?

**Comment by peterpeterparker** [comment]
@jgw96 the 512x512 isn't that really blurry.

source: https://deckdeckgo.com/assets/favicon/android-chrome-512x512.png

maybe some transformations are applied when the splash images are generated? or is it "just" a zooming question (the img on the splash of the pwa is smaller)?

**Comment by andreban** [comment]
I think what may be happening is that the 512x512 image is being stretched to generate an xxhdpi image, which would be 900x900px. An xxxhdpi would be even worse, as it's 1200x1200, but I think that is usually used on tabled devices -  https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/core/src/lib/TwaGenerator.ts#L58-L59

I'll check generation in Bubblewrap (https://github.com/GoogleChromeLabs/bubblewrap) and file the issue there. A solution would be not to generate stretched images and check how the browser will handle smaller images. If the browser stretches it, we may need to generate images with transparent space instead of stretching the icon.

**Comment by andreban** [comment]
Looking at the payload for `generateSignedApk`, it seems to be using the 192x192 image instead of 512x512. I checked out the Bubblewrap CLI, and it uses the 512x512 image.

```json
{
    "packageId": "com.deckdeckgo.twa",
    "host": "deckdeckgo.com",
    "name": "DeckDeckGo",
    "themeColor": "#ffffff",
    "navigationColor": "#ffffff",
    "backgroundColor": "#ffffff",
    "startUrl": "/",
    "iconUrl": "https://deckdeckgo.com/assets/favicon/android-chrome-192x192.png",
    "maskableIconUrl": "https://deckdeckgo.com/assets/favicon/android-chrome-192x192.png",
    "appVersion": "1.0.0",
    "useBrowserOnChromeOS": true,
    "splashScreenFadeOutDuration": 300,
    "enableNotifications": false,
    "shortcuts": [],
    "signingInfo": {
        "fullName": "John Doe",
        "organization": "Contoso",
        "organizationalUnit": "Engineering Department",
        "countryCode": "US"
    }
}
```

Here's what the splash generated by the Bubblewrap CLI looks like:
![Screenshot_20200422-091516](https://user-images.githubusercontent.com/1733592/79958504-e4ef8380-847a-11ea-8a18-8d49838764d2.png)

**Comment by jgw96** [comment]
@andreban ahh ok, interesting. So this is probably a logic issue on our side of things, ill take a look at this. Thanks Andre!

**Comment by jgw96** [comment]
Update: Got a fix here https://github.com/pwa-builder/PWABuilder/commit/e5532a078a2a02f58da342d48608d0b3a7f3d1f5 for this issue. Working on the related issue https://github.com/pwa-builder/CloudAPK/issues/18 and then ill deploy.

**Comment by jgw96** [comment]
Fixed as part of #18

**Comment by peterpeterparker** [comment]
The ratio works like a charm thx to your fix @jgw96 👍

**Comment by peterpeterparker** [comment]
![2020-04-24 19 18 44](https://user-images.githubusercontent.com/16886711/80239434-884dbd80-8660-11ea-89f3-2d951bf83713.jpg)

**Comment by jgw96** [comment]
Epic, thank you! Really appreciate you giving our service a try (:

**Comment by peterpeterparker** [comment]
My pleasure, it's really a great and handy service!
