### ISSUE TITLE
Generating Signed APK failing with `no space left on device`

### ISSUE THREAD

**Issue by andreban** [pwa-builder/CloudAPK#4]
Reproduction Steps:

1.  Enter `https://material.money/` as the URL on the home page and click `start`
2.  Click on 'Build a PWA', then on 'Android', then 'Download'

Expected Behaviour:
An APK is downloaded

Actual Behaviour:
An error message is displayed

```
Error generating signed APK: Error: ENOSPC: no space left on device, copyfile '/app/node_modules/llama-pack/template_project/gradlew' -> '/tmp/pwabuilder-cloudapk-18MEYbrvOJbUzs/gradlew'
```

Generation failed on 3/3 attempts

**Comment by JudahGabriel** [comment]
Thanks! Turns out the Node tmp library we were using for temporary files cleans up after itself...only after restarting Node.

It should work now with our temporary solution in place. @jgw96 and I are working on a permanent fix. Thanks for alerting us, Andre. I'll close this bug when we have our permanent fix in place.

**Comment by ajeetku** [comment]
Error generating signed APK: Error: Could not find MIME for Buffer <null>

**Comment by andreban** [comment]
@ajeetku, this is a different issue, caused by llama-pack, which has been fixed in this PR: https://github.com/GoogleChromeLabs/llama-pack/pull/102. Upgrading to @llama-pack/core 0.4.3 should fix this.

**Comment by jgw96** [comment]
Hello all! This has since been fixed with updated versions of bubblewrap and with our new base docker image https://github.com/pwa-builder/docker-android-build-box .
